### PR TITLE
W-11934998 Removed erroneous == and added information on entryTTL behaviour.

### PR DESCRIPTION
**Pull request by mikeconroy**
# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

### CODE REVIEW

**Comment by mikeconroy** [comment]
Signing the CLA failed with the following error:
image
I tried emailing the address mentioned (contactoss-cla@salesforce.com) but the email bounced.
Now if I try to sign the CLA again I get the following message:
image

**Comment by hannanelson** [comment]
@mike-conroy - Updated with clarification from dev. See also https://docs.mulesoft.com/object-store-connector/1.2/object-store-connector-reference#objectStorev2

**Review by GouthamiKondakindi — APPROVED** [review]
LGTM

**Review by JennyHajee — APPROVED** [review]

**Comment by mikeconroy** [comment]
@hannanelson Thanks for the clarification, I hadn't seen that. Interestingly, that doesn't seem to match actual results in the runtime when I've tested this.

I have a simple flow with an object store which has an entryTTL of -1 seconds & an Expiration Interval of 1 second. The flow will store the value "testPayload" in the OS, wait 12 seconds (arbitrary) and then retrieves the value again. On retrieval, it returns the OS Default Value "nullPayload". I would expect the Retrieve operation to return the stored value "testPayload" if the expiryTTL defaulted to the maximum (30 days).

```
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:os="http://www.mulesoft.org/schema/mule/os"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/os http://www.mulesoft.org/schema/mule/os/current/mule-os.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
	<os:object-store name="os" doc:name="Object store"
		doc:id="8caff084-ee2f-4d62-933e-d4d7758080db" expirationIntervalUnit="SECONDS" entryTtl="-1"/>
	<flow name="object-store-ttlFlow"
		doc:id="9c56b56b-6828-447d-a664-25bb8e24ba10">
		<scheduler doc:name="Scheduler"
			doc:id="bcea3c2b-93c6-4d0d-b18d-a6aee0927266">
			<scheduling-strategy>
				<fixed-frequency frequency="1000000"/>
			</scheduling-strategy>
		</scheduler>
		<logger level="INFO" doc:name="Log Storing Value" doc:id="3f97441c-ed5a-4e26-b111-e95d02ea2c9b" message="Storing Value: testPayload"/>
		<os:store doc:name="Store"
			doc:id="40fda9f0-e7ea-4d29-8476-87a3c9ade5e1" key="testKey"
			objectStore="os">
			<os:value ><![CDATA[#["testPayload"]]]></os:value>
		</os:store>
		<logger level="INFO" doc:name="Log Waiting 12 Seconds" doc:id="7e20acc6-0edf-42b7-b5cb-90ffe3e5547d" message="Waiting 12 Seconds"/>
		<ee:transform doc:name="Wait 12 Seconds" doc:id="b600eaff-0ca6-4324-b50a-45f60d9e6ccb" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
import * from dw::Runtime
output application/java
---
{} wait(12000)]]></ee:set-payload>
			</ee:message>
		</ee:transform>
		<os:retrieve doc:name="Retrieve"
			doc:id="00921ce3-8de0-4aff-8cff-e9077098b053" key="testKey" objectStore="os">
			<os:default-value><![CDATA[nullPayload]]></os:default-value>
		</os:retrieve>
		<logger level="INFO" doc:name="Log Retrieved Value" doc:id="7513451d-d3dd-44ca-b933-be259b148563" message="Retrieved Value: #[payload]"/>
	</flow>
</mule>
```

Deployed to CH 2.0 on 4.4.0:
Screenshot 2022-10-20 at 16 52 02

**Comment by GouthamiKondakindi** [comment]
Hi @mike-conroy , the key should have a ttl of 30 days. I tested the same flow you mentioned but instead of relying on logs, I looked at the actual object store that's created for the app and see the key exists even few minutes after creation.
Screen Shot 2022-10-25 at 5 55 34 PM

If you see different behavior, can you please create a support ticket so that the team can look into it? Thank you!
fyi @yunmei-zhang

**Comment by mikeconroy** [comment]
Thank you @GouthamiKondakindi for checking and validating. I'm not sure why we see different behaviour, I will spend some more time looking at it.

**Comment by yunmei-zhang** [comment]
Hi @mike-conroy, If the issue is reproducible, the following info needs to be collected for further troubleshooting.

1.Application jar file exported from the Anypoint Studio
2.OSv2 debug https://help.mulesoft.com/s/article/What-Information-to-Collect-for-OSv2-Cases#General%20application%20issues
Kindly have the OSv2 debug enabled when deploying the app so it captures all the info needed.

**Pull request merged**
